### PR TITLE
Update the frequency of the transorm publisher

### PR DESCRIPTION
**Pull request by RutgerVanBeek**
## Description

Capture point was quite wiggly, which was of course not so beneficial. One of the reasons was that the joint state publisher and the script publishing the transform from the robot to the world were not publishing at the same rate. This means that the center of mass was updated although TF was only partially updated. This was not a big deal, but when we differentiate this for capture point we get a noisy signal. So ideally the two rates are equal. That does not take away all the noise, but there will be another PR in the march repo with a robust way of differentiating. 
## Changes

Change the frequency of the transform publisher from 10 to 50 and add a comment about it.

### CODE REVIEW

**Review by Olavhaasie — APPROVED** [review]
If you really care about performance you could implement this as a Gazebo plugin. I think the services are not optimal speed and might not be designed for this.

**Comment by RutgerVanBeek** [comment]
> If you really care about performance you could implement this as a Gazebo plugin. I think the services are not optimal speed and might not be designed for this.

I don't think speeds as an issue for now, but it is indeed better to make a plugin for this.

**Review by Roelemans — APPROVED** [review]
How do you know tf frame update rate is 50?

**Comment by Ishadijcks** [comment]
Just because they run at the same rate does not mean that one always updates before the other. In fact you should still expect that half the updates of the center of mass calculation run on stale data

**Pull request merged**
